---
- name: Restart tailscaled
  ansible.builtin.command:
    argv:
      - pct
      - exec
      - "{{ tailscale_client_vmid | string }}"
      - --
      - systemctl
      - restart
      - tailscaled
  changed_when: false
  when: tailscale_client_enabled | default(false) | bool
