---
- name: Check ZFS dataset {{ storage_bind_mount.host_prepare.dataset }}
  ansible.builtin.command:
    argv:
      - zfs
      - list
      - -H
      - -o
      - name
      - "{{ storage_bind_mount.host_prepare.dataset }}"
  register: storage_zfs_list
  changed_when: false
  failed_when: storage_zfs_list.rc not in [0, 1]

- name: Create ZFS dataset {{ storage_bind_mount.host_prepare.dataset }}
  ansible.builtin.command:
    argv:
      - zfs
      - create
      - -o
      - "mountpoint={{ storage_bind_mount.host_prepare.mountpoint }}"
      - "{{ storage_bind_mount.host_prepare.dataset }}"
  when: storage_zfs_list.rc != 0

- name: Read ZFS mountpoint {{ storage_bind_mount.host_prepare.dataset }}
  ansible.builtin.command:
    argv:
      - zfs
      - get
      - -H
      - -o
      - value
      - mountpoint
      - "{{ storage_bind_mount.host_prepare.dataset }}"
  register: storage_zfs_mountpoint
  changed_when: false

- name: Set ZFS mountpoint {{ storage_bind_mount.host_prepare.dataset }}
  ansible.builtin.command:
    argv:
      - zfs
      - set
      - "mountpoint={{ storage_bind_mount.host_prepare.mountpoint }}"
      - "{{ storage_bind_mount.host_prepare.dataset }}"
  when: storage_zfs_mountpoint.stdout != storage_bind_mount.host_prepare.mountpoint

- name: Mount ZFS dataset {{ storage_bind_mount.host_prepare.dataset }}
  ansible.builtin.command:
    argv:
      - zfs
      - mount
      - "{{ storage_bind_mount.host_prepare.dataset }}"
  register: storage_zfs_mount
  changed_when: storage_zfs_mount.rc == 0
  failed_when: storage_zfs_mount.rc not in [0, 1]

- name: Set host storage ownership {{ storage_bind_mount.host_prepare.mountpoint }}
  ansible.builtin.file:
    path: "{{ storage_bind_mount.host_prepare.mountpoint }}"
    state: directory
    owner: "{{ storage_bind_mount.uid }}"
    group: "{{ storage_bind_mount.gid }}"
    mode: "{{ storage_bind_mount.mode | default('0750') }}"
