---
- name: Restart hermes dashboard
  ansible.builtin.systemd:
    name: hermes-dashboard
    state: restarted
    daemon_reload: true
- name: Restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
