#!/usr/bin/env python3
"""Generate and fail-closed validate concise active reconciliation authorities.

The lossless, per-claim reconciliation ledger is frozen in Git history.  Active
reconciliation tracks only package completion, the original audit dispositions,
explicit approved decisions, and environment-specific acceptance evidence.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
RECON = ROOT / ".hermes" / "reconciliation"
AUDIT_PATH = ".hermes/plans/2026-08-04-comprehensive-project-audit.md"
PLAN_PATH = ".hermes/plans/2026-08-04-combined-remediation-and-backlog-reconciliation.md"
# Last committed lossless ledger before P10-A.  It remains inspectable with:
# git show <ref>:.hermes/reconciliation/design-implementation-ledger.json
HISTORICAL_LEDGER = {
    "git_ref": "e04aed2ef2f0133368cdd26ed57d9c9ba3b2a548",
    "path": ".hermes/reconciliation/design-implementation-ledger.json",
    "record_count": 919,
    "purpose": "Frozen lossless per-claim provenance; not regenerated by active documentation updates.",
}
AUDIT_IDS = tuple(
    [f"H{i}" for i in range(1, 13)]
    + [f"M{i}" for i in range(1, 19)]
    + [f"L{i}" for i in range(1, 9)]
)
AUDIT_HEADING = re.compile(r"^###\s+((?:H|M|L)\d+)\.\s+(.+?)\s*$")
DECISION = re.compile(r"^- \*\*Decision (D(?:10|[1-9])) — ([^.]+)\.\*\*")

AUDIT_PACKAGE = {
    "H1":"S1", "H2":"O3", "H3":"O2", "H4":"R1", "H5":"R2", "H6":"S1", "H7":"S2", "H8":"S3", "H9":"O1", "H10":"S2", "H11":"O3", "H12":"S3",
    "M1":"O2", "M2":"R2", "M3":"S3", "M4":"Q1", "M5":"Q1", "M6":"Q2", "M7":"Q2", "M8":"O3", "M9":"Q3", "M10":"S2", "M11":"S2", "M12":"R1", "M13":"S2", "M14":"Q1", "M15":"S1", "M16":"S2", "M17":"CI", "M18":"O1",
    "L1":"R1", "L2":"R2", "L3":"O3", "L4":"CI", "L5":"R2", "L6":"DOCS", "L7":"Q2", "L8":"DOCS",
}

PACKAGES = [
 {"id":"R1","title":"Canonical service-state recovery correctness","priority":"P0","depends_on":["R2"],"files":["scripts/service-state.sh","infra/ansible/playbooks/service-state-backup.yml","infra/ansible/playbooks/service-state-restore.yml","docs/service-state-backup.md","tests/test_service_state.py"]},
 {"id":"R2","title":"Fresh-site validation and scaffold correctness","priority":"P0","depends_on":[],"files":["scripts/validate-values.sh","scripts/workspace-preflight.py","scripts/values.sh","scaffold/README.md","tests/test_documentation_contract.py"]},
 {"id":"S1","title":"Canonical service and stateful ownership","priority":"P0","depends_on":["R2"],"files":["scripts/tfplan-metadata.py","scripts/values_context.py","infra/opentofu/services.tf","tests/test_tfplan_metadata.py"]},
 {"id":"S2","title":"Unified secret contract and preflight","priority":"P0","depends_on":["R2"],"files":["infra/services.json","scripts/secret_delivery.py","scripts/workspace-preflight.py","scripts/secret_bundle_migration.py","tests/test_secret_delivery.py"]},
 {"id":"S3","title":"Plan/apply/teardown integrity and state protection","priority":"P0","depends_on":["S1","S2"],"files":["scripts/apply-infra.sh","scripts/teardown-infra.sh","scripts/tfplan-metadata.py","docs/canonical-teardown.md","tests/test_tfplan_metadata.py"]},
 {"id":"O1","title":"Hermes Control readiness and role contracts","priority":"P1","depends_on":["S2"],"files":["infra/ansible/roles/hermes/tasks/main.yml","infra/ansible/roles/hermes_control/meta/argument_specs.yml","tests/test_hermes_control_role.py"]},
 {"id":"O2","title":"Host-aware Ansible scheduling","priority":"P1","depends_on":["S2"],"files":["scripts/apply-ansible-services.py","tests/test_apply_ansible_services.py"]},
 {"id":"O3","title":"Immutable runtime and image supply chain","priority":"P1","depends_on":["Q3"],"files":["infra/opentofu/modules/debian-vm","infra/ansible/roles/infisical","infra/ansible/roles/sssf","tests/test_tooling_image_integrity.py"]},
 {"id":"Q1","title":"Ansible convergence and check mode","priority":"P1","depends_on":["O1","O2"],"files":[".ansible-lint","infra/ansible/roles/host_identity","scripts/check-direct-service-ansible.py","tests/test_ansible_safety.py"]},
 {"id":"Q2","title":"OpenTofu module and projection contracts","priority":"P1","depends_on":["S1"],"files":["infra/opentofu/modules/debian-vm","infra/opentofu/modules/debian-lxc","scripts/canonical_projections.py","tests/test_canonical_service_authority.py"]},
 {"id":"Q3","title":"Update workflow parity","priority":"P1","depends_on":[],"files":["scripts/update.py","docs/service-update-policy.md","tests/test_update.py"]},
 {"id":"DOCS","title":"Documentation authority and operations","priority":"P2","depends_on":["R1","R2","S1","S3","O1","O2","O3","Q1","Q2","Q3"],"files":["docs/documentation-inventory.json","docs/README.md","docs/service-catalog.md","tests/test_documentation_contract.py"]},
 {"id":"CI","title":"Tooling, CI, and quality gates","priority":"P2","depends_on":["O3","DOCS"],"files":["tools/Dockerfile","tools/pip-bootstrap.lock","tools/requirements.txt","tools/requirements.lock","tools/python-format-files.txt","scripts/validate-public.sh",".github/workflows/validate.yml"]},
]

PACKAGE_EVIDENCE = {
 "R1":{"production":{"path":"scripts/service-state.sh","lines":"1-80"},"verification":{"path":"tests/test_service_state.py","lines":"1-80"}},
 "R2":{"production":{"path":"scripts/workspace-preflight.py","lines":"1-80"},"verification":{"path":"tests/test_workspace_preflight.py","lines":"1-100"}},
 "S1":{"production":{"path":"scripts/tfplan-metadata.py","lines":"1-120"},"verification":{"path":"tests/test_tfplan_metadata.py","lines":"1-140"}},
 "S2":{"production":{"path":"scripts/secret_delivery.py","lines":"1-120"},"verification":{"path":"tests/test_secret_delivery.py","lines":"1-210"}},
 "S3":{"production":{"path":"scripts/execution-snapshot.py","lines":"1-120"},"verification":{"path":"tests/test_tfplan_metadata.py","lines":"180-300"}},
 "O1":{"production":{"path":"infra/ansible/roles/hermes_control/tasks/main.yml","lines":"1-120"},"verification":{"path":"tests/test_hermes_control_role.py","lines":"1-130"}},
 "O2":{"production":{"path":"scripts/apply-ansible-services.py","lines":"84-155"},"verification":{"path":"tests/test_apply_ansible_services.py","lines":"20-70"}},
 "O3":{"production":{"path":"infra/ansible/tasks/reviewed-artifact-cache.yml","lines":"1-62"},"verification":{"path":"tests/test_artifact_projection.py","lines":"1-130"}},
 "Q1":{"production":{"path":"scripts/check-direct-service-ansible.py","lines":"1-120"},"verification":{"path":"tests/test_ansible_convergence_contract.py","lines":"1-100"}},
 "Q2":{"production":{"path":"infra/opentofu/services.tf","lines":"1-170"},"verification":{"path":"tests/test_canonical_service_authority.py","lines":"1-180"}},
 "Q3":{"production":{"path":"scripts/update.py","lines":"1-100"},"verification":{"path":"tests/test_update.py","lines":"1-230"}},
 "DOCS":{"production":{"path":"docs/service-operations.md","lines":"1-70"},"verification":{"path":"tests/test_documentation_contract.py","lines":"39-245"}},
 "CI":{"production":{"path":"tools/Dockerfile","lines":"1-60"},"verification":{"path":"tests/test_phase7_tooling_contract.py","lines":"1-80"}},
}

MATRIX_COLUMNS = (
    "plan", "apply", "health-idempotence", "service-restore",
    "infrastructure-recovery", "hermes-integration", "rollback",
)
MATRIX_ROWS = {
    "development": {
        "plan": "evidenced", "apply": "evidenced",
        "health-idempotence": "evidenced",
        "service-restore": "evidenced",
        "infrastructure-recovery": "evidenced",
        "hermes-integration": "evidenced", "rollback": "evidenced",
    },
    "isolated-recovery": {column: "not-evidenced" for column in MATRIX_COLUMNS},
    "production": {column: "not-evidenced" for column in MATRIX_COLUMNS},
}
DEVELOPMENT_ACCEPTANCE_COMMIT = "9c568a3f03c7a125a3c398e3f6bf5ab860259033"
MATRIX_EVIDENCE = {
    f"development/{category}": {
        "environment": "development",
        "category": category,
        "audited_commit": DEVELOPMENT_ACCEPTANCE_COMMIT,
        "citation": {"path": PLAN_PATH, "lines": lines},
        "procedure_id": procedure,
        "result": "passed",
        "date": "2026-08-22",
        "boundary": boundary,
    }
    for category, lines, procedure, boundary in (
        (
            "plan",
            "635-648",
            "phase-9-gate-1",
            "Disposable development plan only; no prior normalized baseline established semantic equivalence.",
        ),
        (
            "apply",
            "635-648",
            "phase-9-gate-2",
            "Reviewed disposable development apply only; no isolated-recovery or production acceptance.",
        ),
        (
            "health-idempotence",
            "635-648",
            "phase-9-gate-3",
            "Direct development health and second-run idempotence only.",
        ),
        (
            "service-restore",
            "635-648",
            "phase-9-gate-4",
            "Enabled disposable development stateful services only; not controller or infrastructure recovery.",
        ),
        (
            "infrastructure-recovery",
            "635-658",
            "phase-9-gate-5",
            "Disposable development controller/infrastructure recovery rehearsal: private audit and state snapshots were verified and restored through guarded paths, post-recovery canonical convergence and redacted connectivity passed, and fresh provider plans were zero-change. It does not establish independent external audit durability, rollback, or production acceptance.",
        ),
        (
            "hermes-integration",
            "661-674",
            "phase-9-gate-6-read-only-bridge",
            "Disposable development deployed-plugin read-only status and audit verification only; uses a non-secret service-ID context and guest-local private empty audit baseline. It does not establish authenticated dashboard/API or WebSocket acceptance, external audit durability, mutation approval identity, rollback, isolated-recovery, or production acceptance.",
        ),
    )
}
MATRIX_EVIDENCE["development/hermes-integration"]["audited_commit"] = (
    "9c568a3f03c7a125a3c398e3f6bf5ab860259033"
)
MATRIX_EVIDENCE["development/hermes-integration"]["date"] = "2026-08-22"
MATRIX_EVIDENCE["development/plan"]["audited_commit"] = "b25d0037ef510bc848786e18582fab95bf9661fc"
MATRIX_EVIDENCE["development/infrastructure-recovery"]["audited_commit"] = "b25d0037ef510bc848786e18582fab95bf9661fc"
MATRIX_EVIDENCE["development/rollback"] = {
    "environment": "development",
    "category": "rollback",
    "audited_commit": "2249405d2c4a45c3c14cfcff74f2bb6a610c103f",
    "citation": {"path": PLAN_PATH, "lines": "676-687"},
    "procedure_id": "phase-9-gate-7-development-hermes-rollback",
    "result": "passed",
    "date": "2026-08-22",
    "boundary": "Disposable development Hermes managed-release rollback rehearsal only: an intentionally invalid activation entered the guarded rescue path, restored the prior managed venv link, restarted gateway and dashboard, verified local gateway/dashboard health, and was followed by a zero-change provider plan. It does not establish rollback for other services, isolated-recovery, external audit durability, or production acceptance.",
}
RETIRED_ARTIFACTS = (
    "audit-package-evidence-registry.json", "audit-package-evidence-registry.md",
    "backlog.json", "contradiction-register.md", "decision-register.md",
    "dependency-graph.md", "design-implementation-ledger.json",
    "extraction-coverage.md", "source-register.json", "source-register.md",
)
RETIRED_WAVE_OUTPUTS = (
    "01-r1.md", "02-r2.md", "03-s1.md", "04-s2.md", "05-s3.md",
    "06-o1.md", "07-o2.md", "08-o3.md", "09-q1.md", "10-q2.md",
    "11-q3.md", "12-docs.md", "13-ci.md", "14-decisions.md", "15-acceptance.md",
)


def retire_declared_artifacts(reconciliation: Path) -> None:
    """Remove only the retired generated paths named by this migration."""
    for name in RETIRED_ARTIFACTS:
        (reconciliation / name).unlink(missing_ok=True)
    for name in RETIRED_WAVE_OUTPUTS:
        (reconciliation / "waves" / name).unlink(missing_ok=True)


def line_count(path: str) -> int:
    return len((ROOT / path).read_text(encoding="utf-8").splitlines())


def citation_errors(citation: dict[str, str]) -> list[str]:
    path = citation.get("path", "")
    try:
        start, _, end = citation["lines"].partition("-")
        first, last = int(start), int(end or start)
    except (KeyError, ValueError):
        return [f"invalid citation syntax: {path}:{citation.get('lines', '')}"]
    if not (ROOT / path).is_file() or not 1 <= first <= last <= line_count(path):
        return [f"invalid citation range: {path}:{citation.get('lines', '')}"]
    return []


def audit_findings() -> list[dict[str, Any]]:
    findings = []
    for line, text in enumerate((ROOT / AUDIT_PATH).read_text(encoding="utf-8").splitlines(), 1):
        match = AUDIT_HEADING.match(text)
        if not match:
            continue
        finding_id, title = match.groups()
        package = AUDIT_PACKAGE[finding_id]
        findings.append({
            "id": finding_id,
            "title": title,
            "package": package,
            "disposition": "implemented-static",
            "source": {"path": AUDIT_PATH, "lines": str(line)},
            "evidence": {role: {**citation, "role": role} for role, citation in PACKAGE_EVIDENCE[package].items()},
            "external_acceptance": "see acceptance-matrix; static evidence does not establish provider, live, recovery, or production acceptance",
        })
    return findings


def explicit_decisions() -> list[dict[str, str]]:
    decisions = []
    for line, text in enumerate((ROOT / PLAN_PATH).read_text(encoding="utf-8").splitlines(), 1):
        match = DECISION.match(text)
        if match:
            decision_id, title = match.groups()
            decisions.append({"id": decision_id, "title": title, "source": f"{PLAN_PATH}:{line}"})
    return decisions


def build() -> tuple[dict[str, Any], dict[str, Any], dict[str, Any], str]:
    packages = []
    for package in PACKAGES:
        packages.append({
            **package,
            "source_status": "source-complete",
            "evidence": PACKAGE_EVIDENCE[package["id"]],
        })
    findings = audit_findings()
    decisions = explicit_decisions()
    matrix = {
        "environments": list(MATRIX_ROWS),
        "columns": list(MATRIX_COLUMNS),
        "rows": MATRIX_ROWS,
        "evidence": MATRIX_EVIDENCE,
        "evidence_boundary": (
            "Active authority for environment-specific external acceptance only. "
            "An evidenced or historical-evidence cell records a rehearsal at its exact environment, audited commit, "
            "procedure, result, citation, date, and stated boundary; source completion "
            "does not populate this matrix, and later lifecycle changes require revalidation."
        ),
        "development_source": f"{PLAN_PATH}:635-648",
    }
    completion = {
        "schema_version": 1,
        "historical_ledger": HISTORICAL_LEDGER,
        "packages": packages,
        "frontier": [package["id"] for package in packages if package["source_status"] != "source-complete"],
        "unresolved_decisions": [],
        "explicit_decisions": decisions,
        "acceptance_matrix": matrix,
    }
    audit = {"schema_version": 1, "historical_ledger": HISTORICAL_LEDGER, "findings": findings}
    coverage = "Active authority for source-package completion only. Static repository evidence does not establish provider, live-service, recovery, or production acceptance; lossless per-claim provenance is frozen in Git history."
    return completion, audit, completion, coverage


def validate(completion: dict[str, Any], audit: dict[str, Any], _: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    retired = [name for name in RETIRED_ARTIFACTS if (RECON / name).exists()]
    retired.extend(
        f"waves/{name}"
        for name in RETIRED_WAVE_OUTPUTS
        if (RECON / "waves" / name).exists()
    )
    if retired:
        errors.append(f"retired generated artifacts must be absent: {', '.join(sorted(retired))}")
    historical = completion.get("historical_ledger", {})
    ref, path = historical.get("git_ref", ""), historical.get("path", "")
    if not re.fullmatch(r"[0-9a-f]{40}", ref):
        errors.append("historical ledger must use an immutable full Git commit reference")
    elif subprocess.run(["git", "cat-file", "-e", f"{ref}:{path}"], cwd=ROOT).returncode:
        errors.append("historical ledger Git reference is not resolvable")
    packages = completion.get("packages", [])
    package_ids = {package.get("id") for package in packages}
    if "DECISIONS" in package_ids:
        errors.append("DECISIONS package is forbidden when no unresolved decisions remain")
    for package in packages:
        if package.get("source_status") not in {"source-complete", "incomplete"}:
            errors.append(f"invalid package source status: {package.get('id')}")
        for citation in package.get("evidence", {}).values():
            errors.extend(citation_errors(citation))
        for path in package.get("files", []):
            if not (ROOT / path).exists():
                errors.append(f"dangling package file reference: {package['id']} -> {path}")
    expected_frontier = [package["id"] for package in packages if package["source_status"] == "incomplete"]
    if completion.get("frontier") != expected_frontier:
        errors.append("frontier must contain only incomplete source packages")
    decisions = completion.get("explicit_decisions", [])
    if {decision.get("id") for decision in decisions} != {f"D{number}" for number in range(1, 11)}:
        errors.append("explicit decision authority must retain D1 through D10")
    if completion.get("unresolved_decisions"):
        errors.append("unresolved decisions require an explicit DECISIONS package")
    findings = audit.get("findings", [])
    if {finding.get("id") for finding in findings} != set(AUDIT_IDS):
        errors.append("audit finding coverage incomplete")
    for finding in findings:
        if finding.get("package") not in package_ids or finding.get("disposition") not in {"implemented-static", "outstanding", "blocked-external", "superseded"}:
            errors.append(f"invalid audit disposition: {finding.get('id')}")
        if set(finding.get("evidence", {})) != {"production", "verification"}:
            errors.append(f"audit finding lacks production/verification evidence: {finding.get('id')}")
        for citation in finding.get("evidence", {}).values():
            errors.extend(citation_errors(citation))
    matrix = completion.get("acceptance_matrix", {})
    if set(matrix.get("environments", [])) != {"development", "isolated-recovery", "production"}:
        errors.append("acceptance matrix must contain development, isolated-recovery, and production")
    if set(matrix.get("columns", [])) != set(MATRIX_COLUMNS):
        errors.append("acceptance matrix columns are incomplete")
    for environment in matrix.get("environments", []):
        row = matrix.get("rows", {}).get(environment, {})
        if set(row) != set(MATRIX_COLUMNS) or not set(row.values()) <= {"evidenced", "historical-evidence", "not-evidenced"}:
            errors.append(f"invalid acceptance matrix row: {environment}")
    expected_evidence_cells = {
        f"{environment}/{category}"
        for environment in matrix.get("environments", [])
        for category, status in matrix.get("rows", {}).get(environment, {}).items()
        if status in {"evidenced", "historical-evidence"}
    }
    evidence = matrix.get("evidence", {})
    if not isinstance(evidence, dict) or set(evidence) != expected_evidence_cells:
        errors.append("every evidenced acceptance cell must have exactly one evidence record")
    else:
        for cell, record in evidence.items():
            environment, category = cell.split("/", 1)
            if not isinstance(record, dict):
                errors.append(f"invalid acceptance evidence record: {cell}")
                continue
            if record.get("environment") != environment or record.get("category") != category:
                errors.append(f"acceptance evidence cell identity mismatch: {cell}")
            commit = record.get("audited_commit", "")
            if commit != MATRIX_EVIDENCE.get(cell, {}).get("audited_commit") or not re.fullmatch(r"[0-9a-f]{40}", commit):
                errors.append(f"acceptance evidence audited commit mismatch: {cell}")
            elif subprocess.run(
                ["git", "cat-file", "-e", f"{commit}^{{commit}}"], cwd=ROOT
            ).returncode:
                errors.append(f"acceptance evidence commit is not resolvable: {cell}")
            citation = record.get("citation")
            if not isinstance(citation, dict):
                errors.append(f"acceptance evidence citation is missing: {cell}")
            else:
                errors.extend(citation_errors(citation))
            if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", str(record.get("procedure_id", ""))):
                errors.append(f"acceptance evidence procedure is invalid: {cell}")
            if record.get("result") != "passed":
                errors.append(f"acceptance evidence result is not passed: {cell}")
            if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(record.get("date", ""))):
                errors.append(f"acceptance evidence date is invalid: {cell}")
            if not str(record.get("boundary", "")).strip():
                errors.append(f"acceptance evidence boundary is missing: {cell}")
            serialized = json.dumps(record, sort_keys=True)
            if re.search(r"(?:/home/|/workspace/|values/|192\.168\.|10\.\d+\.\d+\.\d+)", serialized):
                errors.append(f"acceptance evidence is not public-safe: {cell}")
    if matrix.get("rows", {}).get("isolated-recovery", {}).get("service-restore") == "historical-evidence":
        errors.append("development service-restore evidence must not be promoted to isolated recovery")
    if matrix.get("rows", {}).get("production", {}).get("service-restore") == "historical-evidence":
        errors.append("development service-restore evidence must not be promoted to production")
    return errors


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    return "\n".join(["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |", *["| " + " | ".join(row) + " |" for row in rows]])


def artifacts(completion: dict[str, Any], audit: dict[str, Any], _: dict[str, Any], coverage: str) -> dict[Path, str]:
    packages = completion["packages"]
    package_rows = [[p["id"], p["title"], p["source_status"], "; ".join(f"{role}: `{item['path']}:{item['lines']}`" for role, item in p["evidence"].items())] for p in packages]
    package_md = "\n".join(["# Package source completion", "", coverage, "", f"Frozen lossless provenance: `git show {HISTORICAL_LEDGER['git_ref']}:{HISTORICAL_LEDGER['path']}` ({HISTORICAL_LEDGER['record_count']} records).", "", markdown_table(["Package", "Title", "Source completion", "Evidence"], package_rows), "", "## Source frontier", "", "No incomplete source packages remain. External acceptance is tracked only in the acceptance matrix.", ""])
    audit_rows = [[f["id"], f["package"], f["disposition"], f"`{f['source']['path']}:{f['source']['lines']}`", "; ".join(f"{role}: `{item['path']}:{item['lines']}`" for role, item in f["evidence"].items())] for f in audit["findings"]]
    audit_md = "\n".join(["# Original audit finding dispositions", "", "All 38 original findings retain package, disposition, and current production/verification citations. External evidence remains in the acceptance matrix.", "", markdown_table(["Finding", "Package", "Disposition", "Audit source", "Evidence"], audit_rows), ""])
    decision_rows = [[decision["id"], decision["title"], f"`{decision['source']}`"] for decision in completion["explicit_decisions"]]
    decisions_md = "\n".join(["# Explicit approved decisions", "", "No unresolved decisions remain; consequently there is no active `DECISIONS` package.", "", markdown_table(["Decision", "Title", "Source"], decision_rows), ""])
    matrix = completion["acceptance_matrix"]
    matrix_rows = [[environment, *[matrix["rows"][environment][column] for column in matrix["columns"]]] for environment in matrix["environments"]]
    evidence_lines = []
    for cell, record in matrix["evidence"].items():
        citation = record["citation"]
        evidence_lines.append(
            f"- `{cell}` — commit `{record['audited_commit']}`; procedure "
            f"`{record['procedure_id']}`; result `{record['result']}` on "
            f"`{record['date']}`; evidence `{citation['path']}:{citation['lines']}`; "
            f"boundary: {record['boundary']}"
        )
    matrix_md = "\n".join(["# Environment-specific acceptance matrix", "", matrix["evidence_boundary"], "", markdown_table(["Environment", *matrix["columns"]], matrix_rows), "", "## Evidence records", "", *evidence_lines, "", f"Development evidence source: `{matrix['development_source']}`. Current evidenced cells apply only to disposable development and do not establish isolated-recovery or production acceptance.", ""])
    backlog_md = "\n".join(["# Evidence-backed canonical backlog", "", "Active reconciliation is intentionally compact. Package source completion, original audit dispositions, approved decisions, and environment acceptance are the active authorities; the full per-claim ledger is frozen in Git history.", "", "- [Package source completion](../.hermes/reconciliation/package-completion.md)", "- [Original audit finding dispositions](../.hermes/reconciliation/audit-dispositions.md)", "- [Explicit approved decisions](../.hermes/reconciliation/explicit-decisions.md)", "- [Environment-specific acceptance matrix](../.hermes/reconciliation/acceptance-matrix.md)", "", "Only external acceptance remains active; no incomplete source package or unresolved decision is reported as frontier work.", ""])
    return {
        RECON / "package-completion.json": json.dumps(completion, indent=2) + "\n",
        RECON / "package-completion.md": package_md,
        RECON / "audit-dispositions.json": json.dumps(audit, indent=2) + "\n",
        RECON / "audit-dispositions.md": audit_md,
        RECON / "explicit-decisions.md": decisions_md,
        RECON / "acceptance-matrix.json": json.dumps(matrix, indent=2) + "\n",
        RECON / "acceptance-matrix.md": matrix_md,
        ROOT / "docs/design-implementation-backlog.md": backlog_md,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    completion, audit, legacy_backlog, coverage = build()
    expected = artifacts(completion, audit, legacy_backlog, coverage)
    if args.write:
        retire_declared_artifacts(RECON)
        for path, content in expected.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    errors = validate(completion, audit, legacy_backlog)
    if args.check:
        for path, content in expected.items():
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                errors.append(f"stale or missing generated artifact: {path.relative_to(ROOT)}; run --write")
    if errors:
        print("\n".join(f"ERROR: {error}" for error in errors), file=sys.stderr)
        return 1
    print(f"reconciliation valid: {len(completion['packages'])} source packages, {len(audit['findings'])} audit findings, {len(completion['explicit_decisions'])} explicit decisions; frontier: {completion['frontier'] or 'external acceptance only'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
