---
infisical_onramp_base_dir: "{{ onramp_host_deploy_dir }}/infisical"
infisical_onramp_container_port: "{{ infisical_container_port | default(8081) }}"
infisical_onramp_bind_address: "{{ infisical_bind_address | default('127.0.0.1') }}"
infisical_onramp_compose_provider_command: "{{ onramp_host_compose_provider_command | default('podman-compose') }}"
infisical_onramp_version: "{{ infisical_version | default('latest') }}"
infisical_onramp_postgres_user: "{{ infisical_postgres_user | default('infisical') }}"
infisical_onramp_postgres_db: "{{ infisical_postgres_db | default('infisical') }}"
infisical_onramp_required_packages: []
