---
- name: Bootstrap Technitium DNS LXC
  hosts: pve
  gather_facts: false
  roles:
    - technitium

- name: Configure Technitium Caddy HTTPS proxy
  hosts: pve
  gather_facts: false
  roles:
    - caddy_proxy

- name: Bootstrap Forgejo LXC
  hosts: pve
  gather_facts: false
  roles:
    - forgejo

- name: Bootstrap Tailscale client LXC
  hosts: pve
  gather_facts: false
  roles:
    - tailscale_client
